# Generated by Django 3.1.7 on 2021-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketeering', '0003_auto_20210319_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='best_bracket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='sum_of_2',
            field=models.IntegerField(default=0),
        ),
    ]
