# Generated by Django 3.1.7 on 2021-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketeering', '0004_auto_20210319_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='elite_eight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bracket',
            name='elite_eight_pot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='streak_winner',
            field=models.BooleanField(default=False),
        ),
    ]
