# Generated by Django 3.1.7 on 2021-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketeering', '0005_auto_20210320_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='payout',
            field=models.FloatField(default=-20),
        ),
    ]
