# Generated by Django 3.1.7 on 2021-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracketeering', '0006_owner_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='max_elite_eight',
            field=models.IntegerField(default=0),
        ),
    ]
