# Generated by Django 3.1.7 on 2021-03-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracketeering', '0007_owner_max_elite_eight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=0)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracketeering.bracket')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracketeering.team')),
            ],
        ),
    ]
